export const PKG_PREFIX = '@gasket-ui'
export const PKG_NAME = 'gasket-ui'
export const PKG_CAMELCASE_NAME = 'GasketUI'
export const PKG_CAMELCASE_LOCAL_NAME = 'GasketUILocale'
export const PKG_BRAND_NAME = 'Gasket UI'
